---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: builtin
    hooks:
      - id: check-json
      - id: pretty-format-json
      - id: check-executables-have-shebangs
  - repo: local
    hooks:
      - id: pytest
        name: 🧪 Running tests and test coverage with pytest
        language: system
        types: [python]
        entry: poetry run pytest
        pass_filenames: false